### ISSUE TITLE
gitlab -> github typo

### ISSUE THREAD

**Issue by alecsharpie** [krokrob/packgenlite#21]
Hey Kevin, 
in the packgenlite/tree/master/packgenlite/data/skeleton/README.md file 

it says both gitlab and github

maybe could just change the gitlab to github?

ie. change..

> Check for {proj} in gitlab.com/{group}. If your project is not set please add it:
> 
> Create a new project on gitlab.com/{group}/{proj}
> Then populate it:

to:

> Check for {proj} in github.com/{group}. If your project is not set please add it:
> 
> Create a new project on github.com/{group}/{proj}
> Then populate it:

Thanks,
Alec

**Comment by krokrob** [comment]
thanks @alecsharpie done ✅
